ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_prs: true
  autoupdate_schedule: weekly
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "socio-economic"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        exclude: ^(.github/|CONTRIBUTORS.md)
  - repo: local
    hooks:
      - id: sort-markdown-list
        name: Sort Markdown List
        entry: python3 sort_markdown_list.py
        language: python
        files: README.md
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        # See options: https://taplo.tamasfe.dev/configuration/formatter-options.html
        args: [--option, "reorder_arrays=true", --option, "reorder_keys=true"]
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.1.1
    hooks:
      - id: zizmor
